# Regression Evaluation Metrics

This notebook contains implementations of common regression metrics used to evaluate the performance of machine learning models. Learn how to calculate and interpret MSE, RMSE, MAE, and MAPE.

## Learning Objectives
- Understand common regression metrics
- Implement metrics from scratch using NumPy
- Use scikit-learn's built-in metric functions
- Compare predictions vs actual values
- Interpret metric results for model evaluation

## Exercise 1: Implement Metrics from Scratch

**Objective:** Create custom implementations of common regression metrics using NumPy.

**Metrics:**
- **MSE (Mean Squared Error)**: Average of squared differences between predictions and actual values
- **RMSE (Root Mean Squared Error)**: Square root of MSE
- **MAE (Mean Absolute Error)**: Average of absolute differences
- **MAPE (Mean Absolute Percentage Error)**: Average percentage error

In [1]:
import numpy as np

def mse(y_true, y_pred):
    """
    Calculate Mean Squared Error (MSE).
    
    MSE = (1/n) * Σ(y_true - y_pred)²
    
    Args:
        y_true: Actual values
        y_pred: Predicted values
        
    Returns:
        float: Mean squared error value
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return np.mean((y_true - y_pred) ** 2)

def rmse(y_true, y_pred):
    """
    Calculate Root Mean Squared Error (RMSE).
    
    RMSE = √MSE
    
    Args:
        y_true: Actual values
        y_pred: Predicted values
        
    Returns:
        float: Root mean squared error value
    """
    return np.sqrt(mse(y_true, y_pred))

def mae(y_true, y_pred):
    """
    Calculate Mean Absolute Error (MAE).
    
    MAE = (1/n) * Σ|y_true - y_pred|
    
    Args:
        y_true: Actual values
        y_pred: Predicted values
        
    Returns:
        float: Mean absolute error value
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return np.mean(np.abs(y_true - y_pred))

def mape(y_true, y_pred):
    """
    Calculate Mean Absolute Percentage Error (MAPE).
    
    MAPE = (1/n) * Σ|((y_true - y_pred) / y_true)| * 100
    
    Args:
        y_true: Actual values (must be non-zero)
        y_pred: Predicted values
        
    Returns:
        float: Mean absolute percentage error value (in percentage)
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("Regression metrics functions defined successfully!")

Regression metrics functions defined successfully!


## Exercise 2: Test Metrics with Sample Data

**Objective:** Evaluate prediction quality using custom metric implementations.

**Concepts:** Comparing predictions, interpreting error metrics

In [2]:
# Test data: actual values vs predictions
y_true = [3, 5, 2.5, 7]
y_pred = [2.5, 5.0, 4.0, 8]

print("=" * 50)
print("CUSTOM IMPLEMENTATION RESULTS")
print("=" * 50)
print(f"\nActual values:    {y_true}")
print(f"Predicted values: {y_pred}")
print("\nMetrics:")
print(f"  MSE  (Mean Squared Error):          {mse(y_true, y_pred):.4f}")
print(f"  RMSE (Root Mean Squared Error):     {rmse(y_true, y_pred):.4f}")
print(f"  MAE  (Mean Absolute Error):         {mae(y_true, y_pred):.4f}")
print(f"  MAPE (Mean Absolute Percentage Error): {mape(y_true, y_pred):.2f}%")

CUSTOM IMPLEMENTATION RESULTS

Actual values:    [3, 5, 2.5, 7]
Predicted values: [2.5, 5.0, 4.0, 8]

Metrics:
  MSE  (Mean Squared Error):          0.8750
  RMSE (Root Mean Squared Error):     0.9354
  MAE  (Mean Absolute Error):         0.7500
  MAPE (Mean Absolute Percentage Error): 22.74%


## Exercise 3: Using scikit-learn Metrics

**Objective:** Use built-in scikit-learn functions to calculate regression metrics.

**Concepts:** Library functions, comparing custom vs library implementations

In [3]:
from sklearn.metrics import (mean_squared_error, mean_absolute_error, 
                             mean_absolute_percentage_error)

y_true = [3, 5, 2.5, 7]
y_pred = [2.5, 5.0, 4.0, 8]

# Calculate using sklearn
mse_sklearn = mean_squared_error(y_true, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)
mae_sklearn = mean_absolute_error(y_true, y_pred)
mape_sklearn = mean_absolute_percentage_error(y_true, y_pred) * 100

print("\n" + "=" * 50)
print("SCIKIT-LEARN IMPLEMENTATION RESULTS")
print("=" * 50)
print("\nMetrics:")
print(f"  MSE  (Mean Squared Error):          {mse_sklearn:.4f}")
print(f"  RMSE (Root Mean Squared Error):     {rmse_sklearn:.4f}")
print(f"  MAE  (Mean Absolute Error):         {mae_sklearn:.4f}")
print(f"  MAPE (Mean Absolute Percentage Error): {mape_sklearn:.2f}%")

print("\n" + "=" * 50)
print("COMPARISON: Custom vs Scikit-learn")
print("=" * 50)
print(f"MSE  - Custom: {mse(y_true, y_pred):.4f}, Sklearn: {mse_sklearn:.4f}")
print(f"RMSE - Custom: {rmse(y_true, y_pred):.4f}, Sklearn: {rmse_sklearn:.4f}")
print(f"MAE  - Custom: {mae(y_true, y_pred):.4f}, Sklearn: {mae_sklearn:.4f}")
print(f"MAPE - Custom: {mape(y_true, y_pred):.2f}%, Sklearn: {mape_sklearn:.2f}%")


SCIKIT-LEARN IMPLEMENTATION RESULTS

Metrics:
  MSE  (Mean Squared Error):          0.8750
  RMSE (Root Mean Squared Error):     0.9354
  MAE  (Mean Absolute Error):         0.7500
  MAPE (Mean Absolute Percentage Error): 22.74%

COMPARISON: Custom vs Scikit-learn
MSE  - Custom: 0.8750, Sklearn: 0.8750
RMSE - Custom: 0.9354, Sklearn: 0.9354
MAE  - Custom: 0.7500, Sklearn: 0.7500
MAPE - Custom: 22.74%, Sklearn: 22.74%


## Exercise 2: Binary Classification Metrics

**Objective:** Implement Binary Cross-Entropy (BCE) loss function for binary classification problems.

**Concepts:**
- Binary classification output format (0 or 1)
- Probability predictions (0 to 1)
- Cross-entropy as a loss function
- Numerical stability with epsilon clipping

In [4]:
import numpy as np

def bce(y_true, y_pred):
    """
    Calculate Binary Cross-Entropy (BCE) loss.
    
    BCE = -(1/n) * Σ[y_true * log(y_pred) + (1 - y_true) * log(1 - y_pred)]
    
    Used for binary classification tasks where output is probability between 0 and 1.
    Epsilon clipping prevents log(0) errors.
    
    Args:
        y_true (array): True binary labels (0 or 1)
        y_pred (array): Predicted probabilities (0 to 1)
        
    Returns:
        float: Binary cross-entropy loss value
        
    Example:
        >>> y_true = [1, 0, 1, 0]
        >>> y_pred = [0.9, 0.2, 0.7, 0.1]
        >>> loss = bce(y_true, y_pred)
        >>> print(f"BCE Loss: {loss:.4f}")
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    # Clip predictions to avoid log(0) and log(1)
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    # Calculate binary cross-entropy
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [5]:
# Test binary cross-entropy with sample data
y_true = [1, 0, 1, 0]
y_pred = [0.9, 0.2, 0.7, 0.1]

print("=" * 50)
print("BINARY CROSS-ENTROPY (Custom Implementation)")
print("=" * 50)
print(f"\nTrue labels:      {y_true}")
print(f"Predicted probs:  {y_pred}")
print(f"\nBinary Cross-Entropy Loss: {bce(y_true, y_pred):.4f}")
print("\nInterpretation:")
print("  - Lower values indicate better predictions")
print("  - Perfect predictions (match actual labels) → BCE ≈ 0")
print("  - Random predictions → BCE ≈ 0.693")

BINARY CROSS-ENTROPY (Custom Implementation)

True labels:      [1, 0, 1, 0]
Predicted probs:  [0.9, 0.2, 0.7, 0.1]

Binary Cross-Entropy Loss: 0.1976

Interpretation:
  - Lower values indicate better predictions
  - Perfect predictions (match actual labels) → BCE ≈ 0
  - Random predictions → BCE ≈ 0.693


In [6]:
# Compare with scikit-learn implementation
from sklearn.metrics import log_loss

y_true = [1, 0, 1, 0]
y_pred = [0.9, 0.2, 0.7, 0.1]

bce_custom = bce(y_true, y_pred)
bce_sklearn = log_loss(y_true, y_pred)

print("\n" + "=" * 50)
print("COMPARISON: Custom vs Scikit-learn")
print("=" * 50)
print(f"\nCustom BCE:      {bce_custom:.4f}")
print(f"Scikit-learn:    {bce_sklearn:.4f}")
print(f"Difference:      {abs(bce_custom - bce_sklearn):.2e}")
print("\n✓ Both implementations produce identical results!")


COMPARISON: Custom vs Scikit-learn

Custom BCE:      0.1976
Scikit-learn:    0.1976
Difference:      0.00e+00

✓ Both implementations produce identical results!


## Exercise 3: Multi-Class Classification Metrics

**Objective:** Implement Categorical Cross-Entropy for multi-class classification.

**Concepts:**
- Multi-class classification (3+ classes)
- Probability distributions across classes
- Cross-entropy formula for multiple classes
- One-hot encoding representation

In [7]:
import numpy as np

# Multi-class classification problem: 3 samples, 3 classes
y_true = [0, 1, 2]   # True class labels
y_pred = [
    [0.7, 0.2, 0.1],  # Sample 1: high prob for class 0
    [0.1, 0.6, 0.3],  # Sample 2: high prob for class 1
    [0.2, 0.3, 0.5]   # Sample 3: high prob for class 2
]

# Calculate cross-entropy (selecting probability of true class for each sample)
cross_entropy = -np.mean([np.log(y_pred[i][y_true[i]]) for i in range(len(y_true))])

print("=" * 50)
print("MULTI-CLASS CROSS-ENTROPY (Without One-Hot Encoding)")
print("=" * 50)
print(f"\nTrue labels:              {y_true}")
print(f"Predicted probabilities:\n{np.array(y_pred)}")
print(f"\nCross-Entropy Loss: {cross_entropy:.4f}")
print("\nHow it works:")
print(f"  Sample 0: y_true=0, P(0)=0.7 → -log(0.7) = {-np.log(0.7):.4f}")
print(f"  Sample 1: y_true=1, P(1)=0.6 → -log(0.6) = {-np.log(0.6):.4f}")
print(f"  Sample 2: y_true=2, P(2)=0.5 → -log(0.5) = {-np.log(0.5):.4f}")
print(f"  Average: {cross_entropy:.4f}")

MULTI-CLASS CROSS-ENTROPY (Without One-Hot Encoding)

True labels:              [0, 1, 2]
Predicted probabilities:
[[0.7 0.2 0.1]
 [0.1 0.6 0.3]
 [0.2 0.3 0.5]]

Cross-Entropy Loss: 0.5202

How it works:
  Sample 0: y_true=0, P(0)=0.7 → -log(0.7) = 0.3567
  Sample 1: y_true=1, P(1)=0.6 → -log(0.6) = 0.5108
  Sample 2: y_true=2, P(2)=0.5 → -log(0.5) = 0.6931
  Average: 0.5202


### Using One-Hot Encoding

One-hot encoding transforms class labels into binary vectors where only the true class position is 1:

Example: For 3 classes and label=1 → [0, 1, 0]

This representation makes cross-entropy calculation consistent across binary and multi-class problems.

In [8]:
import numpy as np

def categorical_cross_entropy(y_true, y_pred):
    """
    Calculate Categorical Cross-Entropy using one-hot encoded labels.
    
    CCE = -(1/n) * Σ Σ[y_true_onehot * log(y_pred)]
    
    Args:
        y_true (array): True class labels (integer indices 0 to num_classes-1)
        y_pred (array): Predicted probabilities, shape (n_samples, n_classes)
        
    Returns:
        float: Categorical cross-entropy loss value
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Convert integer labels to one-hot encoded vectors
    num_classes = y_pred.shape[1]
    y_true_onehot = np.eye(num_classes)[y_true]
    
    # Clip to avoid log(0)
    y_pred = np.clip(y_pred, 1e-10, 1 - 1e-10)
    
    # Calculate categorical cross-entropy
    cross_entropy = -np.mean(np.sum(y_true_onehot * np.log(y_pred), axis=1))
    return cross_entropy

# Test with sample data
y_true = [0, 1, 2]  
y_pred = np.array([
    [0.7, 0.2, 0.1],
    [0.1, 0.6, 0.3],
    [0.2, 0.3, 0.5]
])

print("=" * 50)
print("MULTI-CLASS CROSS-ENTROPY (With One-Hot Encoding)")
print("=" * 50)

# Show one-hot encoding
num_classes = y_pred.shape[1]
y_true_onehot = np.eye(num_classes)[y_true]
print(f"\nOriginal labels:  {list(y_true)}")
print(f"One-hot encoded:\n{y_true_onehot}")

# Calculate using custom function
cce = categorical_cross_entropy(y_true, y_pred)
print(f"\nCategorical Cross-Entropy: {cce:.4f}")

# Verify with scikit-learn
from sklearn.metrics import log_loss
cce_sklearn = log_loss(y_true, y_pred)
print(f"Scikit-learn result:       {cce_sklearn:.4f}")
print(f"\n✓ Results match!")

MULTI-CLASS CROSS-ENTROPY (With One-Hot Encoding)

Original labels:  [0, 1, 2]
One-hot encoded:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Categorical Cross-Entropy: 0.5202
Scikit-learn result:       0.5202

✓ Results match!


## Summary: Regression vs Classification Metrics

| Metric Type | Problem Type | Formula | Use Case |
|-------------|-------------|---------|----------|
| **MSE/RMSE/MAE** | Regression | Difference-based | Predicting continuous values |
| **MAPE** | Regression | Percentage error | Percentage-based error analysis |
| **Binary Cross-Entropy** | Binary Classification | -[p*log(p) + (1-p)*log(1-p)] | Two-class problems |
| **Categorical Cross-Entropy** | Multi-class Classification | -Σ(y_onehot * log(ŷ)) | Multi-class problems |

### Key Takeaways

1. **Regression metrics** measure how close predictions are to actual values
2. **Classification metrics** measure how well probability predictions align with true classes
3. **Cross-entropy** is the standard loss function for classification tasks
4. **One-hot encoding** provides a unified representation for multi-class problems
5. **Custom implementations** help understand how metrics work under the hood
6. **Scikit-learn functions** are optimized and production-ready