# NumPy Array Operations Exercises

This notebook contains exercises focused on NumPy array manipulation and operations, including array creation, reshaping, indexing, type conversion, and concatenation.

## Learning Objectives
- Understand NumPy arrays and their properties
- Work with multi-dimensional arrays
- Reshape arrays efficiently
- Access elements using indexing
- Convert between data types
- Combine arrays using concatenation
- Understand broadcasting and array operations

## Exercise 1: Create and Inspect 3D Arrays

**Objective:** Create a 3D random array and inspect its shape and properties.

**Concepts:** NumPy array creation, random number generation, shape attribute, dimensionality

In [1]:
import numpy as np

# Create a 3D random array (4x5x3)
array_3d = np.random.rand(4, 5, 3)

print("Shape of the 3D array:", array_3d.shape)
print("Total number of elements:", array_3d.size)
print("Number of dimensions:", array_3d.ndim)
print("\nFirst few elements of the array:")
print(array_3d)

Shape of the 3D array: (4, 5, 3)
Total number of elements: 60
Number of dimensions: 3

First few elements of the array:
[[[0.87699531 0.38459293 0.42326976]
  [0.96175584 0.41314018 0.49021548]
  [0.95768946 0.74601028 0.87268981]
  [0.14505507 0.20032588 0.49474031]
  [0.84250524 0.05891265 0.34351561]]

 [[0.21619593 0.99266569 0.51328903]
  [0.20596147 0.62738019 0.91377932]
  [0.27341833 0.62449217 0.71425096]
  [0.96248308 0.6367646  0.65574561]
  [0.41072135 0.75410323 0.34597069]]

 [[0.70062458 0.36498163 0.92397292]
  [0.69738815 0.44683312 0.38299005]
  [0.21588974 0.85537155 0.11077454]
  [0.59166751 0.56018994 0.7138754 ]
  [0.45847552 0.22306021 0.0507006 ]]

 [[0.55344143 0.95602834 0.11625125]
  [0.91016525 0.17423267 0.92616383]
  [0.17413143 0.32654379 0.4542133 ]
  [0.33833363 0.6106245  0.13047936]
  [0.97886638 0.27935431 0.75956697]]]


## Exercise 2: Reshape Arrays

**Objective:** Reshape a 3D array into a 2D array without changing data order.

**Concepts:** Array reshaping, maintaining data, shape transformation

In [2]:
# Create a 3D random array
array_3d = np.random.rand(4, 5, 3)
print("Original 3D array shape:", array_3d.shape)

# Reshape to 2D (20 rows, 3 columns)
# Note: 4 * 5 * 3 = 60 elements → 20 * 3 = 60 elements (maintains data)
array_reshaped = array_3d.reshape(20, 3)
print("Reshaped 2D array shape:", array_reshaped.shape)
print("\nFirst 5 rows of reshaped array:")
print(array_reshaped[:5])

Original 3D array shape: (4, 5, 3)
Reshaped 2D array shape: (20, 3)

First 5 rows of reshaped array:
[[0.99860884 0.39561933 0.15406017]
 [0.09896146 0.53881588 0.69406751]
 [0.91449862 0.68651253 0.624361  ]
 [0.47501835 0.24009124 0.53150876]
 [0.65920456 0.21187089 0.24446237]]


## Exercise 3: Array Indexing

**Objective:** Access elements in a 2D array using indexing notation.

**Concepts:** Array indexing, row-column access, zero-based indexing

In [3]:
# Create a 2D array
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80]])

print("2D array:")
print(arr)
print("\nAccessing element at row 1, column 0:")
print("arr[1][0] =", arr[1][0])
print("arr[1, 0] =", arr[1, 0])  # Alternative indexing notation

print("\nAccessing entire row 0:")
print(arr[0])

print("\nAccessing entire column 2:")
print(arr[:, 2])

2D array:
[[10 20 30 40]
 [50 60 70 80]]

Accessing element at row 1, column 0:
arr[1][0] = 50
arr[1, 0] = 50

Accessing entire row 0:
[10 20 30 40]

Accessing entire column 2:
[30 70]


## Exercise 4: Data Type Conversion

**Objective:** Convert array data types efficiently.

**Concepts:** Type casting, astype() method, data type awareness

In [4]:
# Create an integer array
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80]])

print("Original array (integer type):")
print(f"Data type: {arr.dtype}")
print(arr)

# Convert to float
arr_float = arr.astype(float)

print("\nConverted array (float type):")
print(f"Data type: {arr_float.dtype}")
print(arr_float)

# Convert to int32
arr_int32 = arr.astype(np.int32)
print(f"\nConverted to int32: {arr_int32.dtype}")

Original array (integer type):
Data type: int64
[[10 20 30 40]
 [50 60 70 80]]

Converted array (float type):
Data type: float64
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]

Converted to int32: int32


## Exercise 5: Concatenate Arrays

**Objective:** Combine multiple arrays along an axis.

**Concepts:** Array concatenation, axis parameter, array combining

In [5]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Concatenate along axis 0 (default for 1D arrays)
concatenated = np.concatenate((arr1, arr2))
print("\nConcatenated 1D arrays:", concatenated)

# Example with 2D arrays
arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[5, 6], [7, 8]])

print("\n2D Array 1:")
print(arr_2d_1)
print("\n2D Array 2:")
print(arr_2d_2)

# Concatenate along rows (axis=0)
concat_rows = np.concatenate((arr_2d_1, arr_2d_2), axis=0)
print("\nConcatenated along rows (axis=0):")
print(concat_rows)

# Concatenate along columns (axis=1)
concat_cols = np.concatenate((arr_2d_1, arr_2d_2), axis=1)
print("\nConcatenated along columns (axis=1):")
print(concat_cols)

Array 1: [1 2 3]
Array 2: [4 5 6]

Concatenated 1D arrays: [1 2 3 4 5 6]

2D Array 1:
[[1 2]
 [3 4]]

2D Array 2:
[[5 6]
 [7 8]]

Concatenated along rows (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns (axis=1):
[[1 2 5 6]
 [3 4 7 8]]
